[package]
name = "zed-hub-markdown"
version = "0.0.1"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
# https://crates.io/crates/zed_extension_api
zed_extension_api = "0.7.0"

regex = "1"
lazy_static = "1.4"
