id = "HubMarkdown"
name = "Hub Markdown"
version = "0.0.1"
schema_version = 1
authors = ["hub33k <hub33k@yahoo.com>"]
description = "Markdown extension by hub33k"
repository = "https://github.com/hub33k/zed-extensions/tree/master/extensions/HubMarkdown"
